[environments]
  [environments.development]
    name = "demodraftmvc"
    namespace = "draftdemo"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
