apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: demo-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: srajaram@pivotal.io
    privateKeySecretRef:
      name: demo-staging
    http01: {}