apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - testswagger.smanyamr.com
  - consumeme.smanyamr.com
  acme:
    config:
    - http01:
        ingressClass: none
      domains:
      - testswagger.smanyamr.com
      - consumeme.smanyamr.com
  issuerRef:
    name: demo-staging
    kind: ClusterIssuer